FROM python:3.8-alpine

RUN python -m pip install --upgrade wheel

COPY . .

RUN python -m pip install -r requirements.txt

RUN mkdir test-files
RUN mkdir test-files/delete-me
RUN mkdir test-files/my-test
RUN touch test-files/delete-me.txt
RUN printf "THIS WORD NEED BE CHANGED BY setup_test.py -> my-great-test." > test-files/my-test.txt

CMD ["python", "-m", "unittest", "test.py"]